apiVersion: batch/v1
kind: Job
metadata:
  name: seq2seq-job
spec:
  template:
    spec:
      containers:
      - name: demo
        image: gitlab-registry.nautilus.optiputer.net/prp/jupyterlab
        command:
        - "python"
        args:
        - "/opt/repo/Nautilus-seq2seq/main-test.py"
        volumeMounts:
        - name: git-repo
          mountPath: /opt/repo
        resources:
          limits:
            memory: 32Gi
            cpu: "6"
            nvidia.com/gpu: "1"
          requests:
            memory: 24Gi
            cpu: "1"
            nvidia.com/gpu: "1"    
      initContainers:
      - name: init-clone-repo
        image: alpine/git
        args:
          - clone
          - --single-branch
          - https://gitlab.nautilus.optiputer.net/raulgiovannymartinez/Nautilus-seq2seq
          - /opt/repo/Nautilus-seq2seq
        volumeMounts:
          - name: git-repo
            mountPath: /opt/repo
        volumeMounts:
          - mountPath: /models-vol
            name: models-vol
      volumes:
      - name: git-repo
        emptyDir: {}
      volumes:
      - name: models-vol
        persistentVolumeClaim:
          claimName: models-vol
      restartPolicy: Never
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: gpu-type
                operator: In
                values:
                - 2080Ti
  backoffLimit: 3
