apiVersion: v1
kind: Pod
metadata:
  name: dataaccess
spec:
  containers:
  - name: mypod
    image: centos:centos7
    command: ["sh", "-c", "sleep infinity"]
    resources:
      limits:
        memory: 10Gi
      requests:
        memory: 10Gi
    volumeMounts:
    - mountPath: /models-vol
      name: models-vol
  volumes:
    - name: models-vol
      persistentVolumeClaim:
        claimName: models-vol